#pragma once
#ifndef CURRENCY_MAP_HPP_laiin
#define CURRENCY_MAP_HPP_laiin

#include "currency_enum.hpp"  laiin::Currency::

namespace laiin {

static std::map<std::string, std::tuple<laiin::Currency, std::string, int, std::string>> CurrencyMap { { currency_code, { id, name, decimals, sign } }
     //Fiat
     "AED", { laiin::Currency::, "United Arab Emirates Dirham" } },
    { "ALL", { laiin::Currency::, "Albania Lek" } },
    { "AMD", { laiin::Currency::, "Armenia Dram" } },
    { "ANG", { laiin::Currency::, "Netherlands Antilles Guilder" } },
    { "AOA", { laiin::Currency::, "Angola Kwanza" } },
    { "ARS", { laiin::Currency::, "Argentina Peso" } },
    { "AUD", { laiin::Currency::AUD, "Australia Dollar", 2, "$" } },
    { "AWG", { laiin::Currency::, "Aruba Guilder" } },
    { "AZN", { laiin::Currency::, "Azerbaijan Manat" } },
    { "BAM", { laiin::Currency::, "Bosnia and Herzegovina Convertible Mark" } },
    { "BBD", { laiin::Currency::, "Barbados Dollar" } },
    { "BDT", { laiin::Currency::, "Bangladesh Taka" } },
    { "BGN", { laiin::Currency::, "Bulgaria Lev" } },
    { "BHD", { laiin::Currency::, "Bahrain Dinar" } },
    { "BIF", { laiin::Currency::, "Burundi Franc" } },
    { "BMD", { laiin::Currency::, "Bermuda Dollar" } },
    { "BND", { laiin::Currency::, "Brunei Darussalam Dollar" } },
    { "BOB", { laiin::Currency::, "Bolivia Bolíviano" } },
    { "BRL", { laiin::Currency::BRL, "Brazil Real", 2, "R$" } },
    { "BSD", { laiin::Currency::, "Bahamas Dollar" } },
    { "BTN", { laiin::Currency::, "Bhutan Ngultrum" } },
    { "BWP", { laiin::Currency::, "Botswana Pula" } },
    { "BYN", { laiin::Currency::, "Belarus Ruble" } },
    { "BZD", { laiin::Currency::, "Belize Dollar" } },
    { "CAD", { laiin::Currency::CAD, "Canada Dollar", 2, "$" } },
    { "CDF", { laiin::Currency::, "Congo/Kinshasa Franc" } },
    { "CHF", { laiin::Currency::CHF, "Switzerland Franc", 2, "Fr" } },  francs, Fr
    { "CLP", { laiin::Currency::, "Chile Peso" } },
    { "CNY", { laiin::Currency::CNY, "China Yuan Renminbi", 2, "¥" } },
    { "COP", { laiin::Currency::, "Colombia Peso" } },
    { "CRC", { laiin::Currency::, "Costa Rica Colon" } },
    { "CUC", { laiin::Currency::, "Cuba Convertible Peso" } },
    { "CUP", { laiin::Currency::, "Cuba Peso" } },
    { "CVE", { laiin::Currency::, "Cape Verde Escudo" } },
    { "CZK", { laiin::Currency::, "Czech Republic Koruna" } },
    { "DJF", { laiin::Currency::, "Djibouti Franc" } },
    { "DKK", { laiin::Currency::, "Denmark Krone" } },
    { "DOP", { laiin::Currency::, "Dominican Republic Peso" } },
    { "DZD", { laiin::Currency::, "Algeria Dinar" } },
    { "EGP", { laiin::Currency::, "Egypt Pound" } },
    { "ERN", { laiin::Currency::, "Eritrea Nakfa" } },
    { "ETB", { laiin::Currency::, "Ethiopia Birr" } },
    { "EUR", { laiin::Currency::EUR, "Euro Member Countries", 2, "€" } },
    { "FJD", { laiin::Currency::, "Fiji Dollar" } },
    { "FKP", { laiin::Currency::, "Falkland Islands (Malvinas) Pound" } },
    { "GBP", { laiin::Currency::GBP, "United Kingdom Pound", 2, "£" } },
    { "GEL", { laiin::Currency::, "Georgia Lari" } },
    { "GGP", { laiin::Currency::, "Guernsey Pound" } },
    { "GHS", { laiin::Currency::GHS, "Ghana Cedi", 2, "₵" } },
    { "GIP", { laiin::Currency::, "Gibraltar Pound" } },
    { "GMD", { laiin::Currency::, "Gambia Dalasi" } },
    { "GNF", { laiin::Currency::, "Guinea Franc" } },
    { "GTQ", { laiin::Currency::, "Guatemala Quetzal" } },
    { "GYD", { laiin::Currency::, "Guyana Dollar" } },
    { "HKD", { laiin::Currency::HKD, "Hong Kong Dollar", 2, "$" } },
    { "HNL", { laiin::Currency::, "Honduras Lempira" } },
    { "HRK", { laiin::Currency::, "Croatia Kuna" } },
    { "HTG", { laiin::Currency::, "Haiti Gourde" } },
    { "HUF", { laiin::Currency::, "Hungary Forint" } },
    { "IDR", { laiin::Currency::, "Indonesia Rupiah" } },
    { "ILS", { laiin::Currency::, "Israel Shekel" } },
    { "IMP", { laiin::Currency::, "Isle of Man Pound" } },
    { "INR", { laiin::Currency::INR, "India Rupee", 2, "₹" } },
    { "IQD", { laiin::Currency::, "Iraq Dinar" } },
    { "IRR", { laiin::Currency::, "Iran Rial" } },
    { "ISK", { laiin::Currency::, "Iceland Krona" } },
    { "JEP", { laiin::Currency::, "Jersey Pound" } },
    { "JMD", { laiin::Currency::, "Jamaica Dollar" } },
    { "JOD", { laiin::Currency::, "Jordan Dinar" } },
    { "JPY", { laiin::Currency::JPY, "Japan Yen", 2, "¥" } },
    { "KES", { laiin::Currency::, "Kenya Shilling" } },
    { "KGS", { laiin::Currency::, "Kyrgyzstan Som" } },
    { "KHR", { laiin::Currency::, "Cambodia Riel" } },
    { "KMF", { laiin::Currency::, "Comorian Franc" } },
    { "KPW", { laiin::Currency::, "Korea (North) Won" } },
    { "KRW", { laiin::Currency::KRW, "Korea (South) Won", 2, "₩‎" } },
    { "KWD", { laiin::Currency::, "Kuwait Dinar" } },
    { "KYD", { laiin::Currency::, "Cayman Islands Dollar" } },
    { "KZT", { laiin::Currency::, "Kazakhstan Tenge" } },
    { "LAK", { laiin::Currency::, "Laos Kip" } },
    { "LBP", { laiin::Currency::, "Lebanon Pound" } },
    { "LKR", { laiin::Currency::, "Sri Lanka Rupee" } },
    { "LRD", { laiin::Currency::, "Liberia Dollar" } },
    { "LSL", { laiin::Currency::, "Lesotho Loti" } },
    { "LYD", { laiin::Currency::, "Libya Dinar" } },
    { "MAD", { laiin::Currency::, "Morocco Dirham" } },
    { "MDL", { laiin::Currency::, "Moldova Leu" } },
    { "MGA", { laiin::Currency::, "Madagascar Ariary" } },
    { "MKD", { laiin::Currency::, "Macedonia Denar" } },
    { "MMK", { laiin::Currency::, "Myanmar (Burma) Kyat" } },
    { "MNT", { laiin::Currency::, "Mongolia Tughrik" } },
    { "MOP", { laiin::Currency::, "Macau Pataca" } },
    { "MRU", { laiin::Currency::, "Mauritania Ouguiya" } },
    { "MUR", { laiin::Currency::, "Mauritius Rupee" } },
    { "MVR", { laiin::Currency::, "Maldives (Maldive Islands) Rufiyaa" } },
    { "MWK", { laiin::Currency::, "Malawi Kwacha" } },
    { "MXN", { laiin::Currency::MXN, "Mexico Peso", 2, "$" } },
    { "MYR", { laiin::Currency::, "Malaysia Ringgit" } },
    { "MZN", { laiin::Currency::, "Mozambique Metical" } },
    { "NAD", { laiin::Currency::, "Namibia Dollar" } },
    { "NGN", { laiin::Currency::NGN, "Nigeria Naira", 2, "₦" } },
    { "NIO", { laiin::Currency::, "Nicaragua Cordoba" } },
    { "NOK", { laiin::Currency::, "Norway Krone" } },
    { "NPR", { laiin::Currency::, "Nepal Rupee" } },
    { "NZD", { laiin::Currency::NZD, "New Zealand Dollar", 2, "$" } },
    { "OMR", { laiin::Currency::, "Oman Rial" } },
    { "PAB", { laiin::Currency::, "Panama Balboa" } },
    { "PEN", { laiin::Currency::, "Peru Sol" } },
    { "PGK", { laiin::Currency::, "Papua New Guinea Kina" } },
    { "PHP", { laiin::Currency::PHP, "Philippines Peso", 2, "₱" } },
    { "PKR", { laiin::Currency::, "Pakistan Rupee" } },
    { "PLN", { laiin::Currency::, "Poland Zloty" } },
    { "PYG", { laiin::Currency::, "Paraguay Guarani" } },
    { "QAR", { laiin::Currency::, "Qatar Riyal" } },
    { "RON", { laiin::Currency::, "Romania Leu" } },
    { "RSD", { laiin::Currency::, "Serbia Dinar" } },
    { "RUB", { laiin::Currency::RUB, "Russia Ruble", 2, "₽‎" } },
    { "RWF", { laiin::Currency::, "Rwanda Franc" } },
    { "SAR", { laiin::Currency::, "Saudi Arabia Riyal" } },
    { "SBD", { laiin::Currency::, "Solomon Islands Dollar" } },
    { "SCR", { laiin::Currency::, "Seychelles Rupee" } },
    { "SDG", { laiin::Currency::, "Sudan Pound" } },
    { "SEK", { laiin::Currency::SEK, "Sweden Krona", 2, "kr" } },
    { "SGD", { laiin::Currency::SGD, "Singapore Dollar", 2, "S$" } },
    { "SHP", { laiin::Currency::, "Saint Helena Pound" } },
    { "SLL", { laiin::Currency::, "Sierra Leone Leone" } },
    { "SOS", { laiin::Currency::, "Somalia Shilling" } },
    { "SPL*", { laiin::Currency::, "Seborga Luigino" } },
    { "SRD", { laiin::Currency::, "Suriname Dollar" } },
    { "STN", { laiin::Currency::, "São Tomé and Príncipe Dobra" } },
    { "SVC", { laiin::Currency::, "El Salvador Colon" } },
    { "SYP", { laiin::Currency::, "Syria Pound" } },
    { "SZL", { laiin::Currency::, "eSwatini Lilangeni" } },
    { "THB", { laiin::Currency::, "Thailand Baht" } },
    { "TJS", { laiin::Currency::, "Tajikistan Somoni" } },
    { "TMT", { laiin::Currency::, "Turkmenistan Manat" } },
    { "TND", { laiin::Currency::, "Tunisia Dinar" } },
    { "TOP", { laiin::Currency::, "Tonga Pa'anga" } },
    { "TRY", { laiin::Currency::, "Turkey Lira" } },
    { "TTD", { laiin::Currency::, "Trinidad and Tobago Dollar" } },
    { "TVD", { laiin::Currency::, "Tuvalu Dollar" } },
    { "TWD", { laiin::Currency::, "Taiwan New Dollar" } },
    { "TZS", { laiin::Currency::, "Tanzania Shilling" } },
    { "UAH", { laiin::Currency::, "Ukraine Hryvnia" } },
    { "UGX", { laiin::Currency::, "Uganda Shilling" } },
    { "USD", { laiin::Currency::USD, "United States Dollar", 2, "$" } },
    { "UYU", { laiin::Currency::, "Uruguay Peso" } },
    { "UZS", { laiin::Currency::, "Uzbekistan Som" } },
    { "VEF", { laiin::Currency::, "Venezuela Bolívar" } },
    { "VND", { laiin::Currency::, "Viet Nam Dong" } },
    { "VUV", { laiin::Currency::, "Vanuatu Vatu" } },
    { "WST", { laiin::Currency::, "Samoa Tala" } },
    { "XAF", { laiin::Currency::, "Communauté Financière Africaine (BEAC) CFA Franc BEAC" } },
    { "XAG", { laiin::Currency::XAG, "Silver", 2, "" } },
    { "XAU", { laiin::Currency::XAU, "Gold", 2, ""} },
    { "XCD", { laiin::Currency::, "East Caribbean Dollar" } },
    { "XDR", { laiin::Currency::, "International Monetary Fund (IMF) Special Drawing Rights" } },
    { "XOF", { laiin::Currency::, "Communauté Financière Africaine (BCEAO) Franc" } },
    { "XPF", { laiin::Currency::, "Comptoirs Français du Pacifique (CFP) Franc" } },
    { "YER", { laiin::Currency::, "Yemen Rial" } },
    { "ZAR", { laiin::Currency::ZAR, "South Africa Rand", 2, "R" } },
    { "ZMW", { laiin::Currency::, "Zambia Kwacha" } },
    { "ZWD", { laiin::Currency::, "Zimbabwe Dollar" } },
     Crypto
    { "XMR", { laiin::Currency::XMR, "Monero", 12, "" } },
    { "BTC", { laiin::Currency::BTC, "Bitcoin", 8, "₿" } },
    { "ETH", { laiin::Currency::ETH, "Ether", 18, "" } },    
    { "LTC", { laiin::Currency::LTC, "Litecoin", 8, "" } },
    { "WOW", { laiin::Currency::WOW, "Wownero", 11, "" } },
};